stages:
  - build
  - deploy

variables:
  NODE_ENV: production
  DOCKER_DRIVER: overlay2

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache make
  script:
    - echo "🔨 Building on branch $CI_COMMIT_BRANCH"
    - |
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        make build-production
      elif [ "$CI_COMMIT_BRANCH" = "dev" ]; then
        make build-development
      else
        echo "No build for this branch: $CI_COMMIT_BRANCH"
      fi
    - echo "🛖 Build completed"

deploy_app:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache make
  script:
    - echo "🚀 Deploying..."
    - |
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        make start-production
      elif [ "$CI_COMMIT_BRANCH" = "dev" ]; then
        make start-development
      else
        echo "No build for this branch: $CI_COMMIT_BRANCH"
      fi
    - echo "🌞 Deployment completed"
